version: "3.9"

services:

  kstack-agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      #- /usr/local/bin/docker:/usr/bin/docker:ro
      #- /usr/local/bin/docker-compose:/usr/bin/docker-compose:ro
      - ./data:/app/data
    privileged: true
    user: root
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AGENT_HOST=0.0.0.0
      - AGENT_PORT=5000
      - AGENT_DATA_DIR=/app/data
    labels:
      - "kstack.agent=true"
      - "kstack.protected=true"

#  hello:
#    image: hello-world
#
#  cowsay:
#    image: xshell/cowsay
#    command: ['cowsay', 'wooooooooow']
#
#  whalesay:
#    image: docker/whalesay
#    command: ['cowsay', 'weeeeeeeeee']
#
#  redis:
#    image: redis:latest
#    restart: unless-stopped
#    ports:
#      - "6379:6379"
#    #volumes:
#    #  - './data/redis:/data'
#    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
#
#
#  database:
#    image: mariadb:latest
#    restart: unless-stopped
#    ports:
#      - "3307:3306"
#    #volumes:
#    #  - ./data/mariadb/mysql:/var/lib/mysql
#    #  - ./data/mariadb/initdb.d/:/docker-entrypoint-initdb.d/
#    environment:
#      - MYSQL_ROOT_PASSWORD=docker
#      - MYSQL_PASSWORD=docker
#      - MYSQL_USER=docker
#      - MYSQL_DATABASE=docker