
services:

  agent:
    #privileged: true
    #user: root
    build:
      context: .
      dockerfile: Dockerfile-alpine
    image: kstack-agent-dev
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # for docker engine access
      - /var/lib/docker/volumes:/var/lib/docker/volumes:ro # for docker volume access
      - $PWD/bin:/app/bin:ro
      - $PWD/src:/app/src:ro
      - $PWD/agent.py:/app/agent.py:ro
      - $PWD/celery_worker.sh:/app/celery_worker.sh:ro
      - $PWD/data:/app/data
      #- kstack_agent_data:/app/data
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AGENT_HOST=0.0.0.0
      #- AGENT_PORT=5000
      #- AGENT_DATA_DIR=/app/data
    #healthcheck:
    #  test: curl --fail -s http://localhost:5000/ || exit 1
    #  interval: 1m30s
    #  timeout: 10s
    #  retries: 3


  #  redis:
  #    image: redis:latest
  #    restart: unless-stopped
  #    ports:
  #      - "6379:6379"
  #    #volumes:
  #    #  - './data/redis:/data'
  #    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]


#volumes:
#  kstack_agent_data:
#  redis_data:
