FROM python:3.13-slim

#ENV AGENT_HOST=0.0.0.0
#ENV AGENT_PORT=5000

# Update package list and install necessary dependencies
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y \
    curl \
    gnupg2 \
    lsb-release \
    ca-certificates \
    nginx \
    redis-server \
    supervisor \
    openssl

# Add Docker's official GPG key:
RUN install -m 0755 -d /etc/apt/keyrings \
    && curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc \
    && chmod a+r /etc/apt/keyrings/docker.asc

# Add the repository to Apt sources:
RUN echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
RUN apt-get update && apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /var/cache/apt/archives/*

# Verify the installations
#RUN which docker && docker --version

WORKDIR /app

# Install dependencies
COPY ./pyproject.toml ./poetry.lock /app/
RUN pip install poetry \
    && poetry config virtualenvs.create false \
    && poetry install --only main --no-root

# Copy the rest of the code
#COPY ./src /app/src
#COPY ./agent.py /app/agent.py
#COPY ./README.md /app/README.md

# Configure Supervisor
COPY docker/supervisor/celery_worker.ini /etc/supervisor/conf.d/celery_worker.conf

# Entry point
COPY ./docker/entrypoint.sh /entrypoint.sh
RUN ["chmod", "+x", "/entrypoint.sh"]
ENTRYPOINT ["/entrypoint.sh"]
CMD ["devserver"]


HEALTHCHECK CMD curl --fail http://localhost:5000/ || exit 1

EXPOSE 5000
